### ISSUE TITLE
KaTeX with Tailwind.css

### ISSUE THREAD

**Issue by basilgass** [KaTeX/KaTeX#2731]
**Describe the bug:**
When using tailwind.css as stylesheet, the fraction line and other related "border-color" are rendered greyed.

This is due to the fact that tailwind.css starts with:

```
*,
::before,
::after {
  box-sizing: border-box; /* 1 */
  border-width: 0; /* 2 */
  border-style: solid; /* 2 */
  border-color: #d2d6dc; /* 2 */
}
```

The simple solution is to add the followind line in a custom css:

```
.frac-line{border-color: black !important;}
```

Don't know if there is a cleaner or better way to do this.

**Comment by ronkok** [comment]
@basilgass We added this line:

```
.katex { border-color: currentColor; }
```

to the KaTeX CSS in version v0.12.0, released on July 12. You might check your version of KaTeX, because that line was meant to resolve exactly your problem. If that isn't sufficient, I'm not sure what the next step would be. I don't know if we want to get into a battle of dueling `!important` rules.

**Comment by basilgass** [comment]
I'm using v0.12.0. After some tests, the ```!important``` key seems not needed.

The fact is if I remove the following line from my genereated app.css with tailwind.css content: ```border-color: #d2d6dc; /* 2 */```, the fraction lines are working correctly. I think the main problem is that tailwind.css defines a default border-color for the whole app/website. And the fraction lines are using this default border color...

**Comment by edemaine** [comment]
This is fixed on the master branch, and will be in the next release (0.13.1, hopefully out soon).

**Comment by Cy-47** [comment]
Hi, I'm using katex 0.16.11 with tailwindcss ^3.4.10, and this still happens to me.
